import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gameria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"/>
      </Head>

			{/* Header (Navbar) */}

      <main className={styles.main}>
        <p className={styles.descriptionFirst}>
          Bem-vindo ao
        </p>

        <h1 className={styles.title}>
          GAMERIA
        </h1>

        <p className={styles.description}>
          aqui nós vivemos o universo gamer
        </p>

        <p className={styles.descriptionThird}>
          em construção
        </p>

        {/*<div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &larr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &times;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
					
          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>*/}
      </main>

      <footer className={styles.footer}>
        <p>Carinhosamente feito por <a 
        href="https://github.com/andreiammoraes" target="_blank">Andréia</a> e <a 
        href="https://github.com/rabispedro" target="_blank">Pedro</a>
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span> */}
        </p>
      </footer>
    </div>
  )
}
